name: DAST

on:
  push:
    branches:
    - "main"
    - "master"

permissions:
  issues: write
  contents: read

jobs:
  scan:
    if: ${{ vars.ENABLE_WORKFLOWS == 'true' }}
    uses: General-Magick-Industries/remote-cicd-workflows/.github/workflows/dast.yml@main
    secrets: inherit
